version: '3.8'

services:

  traefik:
    image: traefik:v2.9
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/:/etc/traefik/certs/:ro
      - ./conf/traefik_static_conf.yml:/traefik.yml:ro
      - ./conf/:/etc/traefik/conf/:ro
