version: '3.8'


services:
  nginx:
    image: nginx:1.23.1
    ports:
      - target: 443
        published: 443
        mode: host
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    extra_hosts:
    - "host.docker.internal:host-gateway"
    