version: '3.8'

networks:
  external-pk_network:
    external: true

services:
  nginx:
    image: nginx:1.23.1
    ports:
      - 3000:443
    networks:
      - external-pk_network
    volumes:
      - ./conf/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./certs:/etc/nginx/certs
