
# configure logs
log:
  level: INFO # Set to 'DEBUG' for troubleshooting
  
accessLog: {}

# configure entry points
entryPoints:
  web:
    address: ":80"
    http:
      redirections: # http to https redirection
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"


# configure providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" # connection to the docker daemon
    exposedByDefault: false # ignore containers without label 'traefik.enable=true'
    # network: default
  file:
    directory: "/etc/traefik/conf" # directory for dynamic traefik configuration files
    watch: true # changes are processed immediately

# configure api service
# api:
#   dashboard: true # enable the traefik dashboard


